const { PrismaClient } = require('@prisma/client');
const mockListings = [
    {
        title: 'Luxury Villa with Ocean View',
        location: 'Malibu, California',
        price: 350,
        rating: 4.9,
        type: 'Amazing pools',
        lat: 34.0259,
        lng: -118.7798,
        images: [
            'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1613490493576-7fde63acd811?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
        ],
        amenities: ['Pool', 'Ocean View', 'WiFi', 'Kitchen', 'Hot Tub', 'BBQ Grill'],
        tags: ['beach', 'ocean', 'luxury', 'california', 'usa', 'coastal', 'romantic'],
        description: 'Experience the ultimate luxury in this stunning villa overlooking the ocean. Featuring a private infinity pool, spacious living areas, and breathtaking views.',
        wifiStrength: 9.5,
        noiseLevel: 2.0,
        workspaceRating: 8.0,
        petAllowed: true,
        petSize: 'any',
        petAmenities: ['Fenced yard', 'Pet bowls'],
        nearbyParks: true,
        spaceSize: 3500,
        luxuryAmenities: ['Infinity Pool', 'Chef Kitchen', 'Wine Cellar'],
        romanticScore: 9.8,
        familyScore: 8.5,
        adventureScore: 6.0
    },
    {
        title: 'Cozy Mountain Cabin',
        location: 'Aspen, Colorado',
        price: 220,
        rating: 4.8,
        type: 'Cabins',
        lat: 39.1911,
        lng: -106.8175,
        images: [
            'https://images.unsplash.com/photo-1449156493391-d2cfa28e468b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1510798831971-661eb04b3739?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
        ],
        amenities: ['Mountain View', 'Fireplace', 'WiFi', 'Hiking Trails'],
        tags: ['mountain', 'cabin', 'colorado', 'usa', 'ski', 'adventure', 'romantic'],
        description: 'Escape to the mountains in this cozy cabin. Perfect for a romantic getaway or a family vacation.',
        wifiStrength: 7.0,
        noiseLevel: 1.0,
        workspaceRating: 6.0,
        petAllowed: true,
        petSize: 'large',
        petAmenities: ['Dog bed', 'Treats'],
        nearbyParks: true,
        spaceSize: 1200,
        luxuryAmenities: ['Hot Tub', 'Fireplace'],
        romanticScore: 9.5,
        familyScore: 7.0,
        adventureScore: 9.5
    },
    {
        title: 'Modern Apartment in City Center',
        location: 'New York, New York',
        price: 180,
        rating: 4.7,
        type: 'Iconic cities',
        lat: 40.7128,
        lng: -74.0060,
        images: [
            'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
        ],
        amenities: ['City View', 'WiFi', 'Kitchen', 'Elevator', 'Gym'],
        tags: ['city', 'urban', 'newyork', 'usa', 'modern', 'business'],
        description: 'Stay in the heart of the city in this modern apartment. Close to all major attractions and public transport.',
        wifiStrength: 9.8,
        noiseLevel: 7.5,
        workspaceRating: 9.5,
        petAllowed: false,
        petSize: null,
        petAmenities: [],
        nearbyParks: true,
        spaceSize: 850,
        luxuryAmenities: ['Smart Home', 'Concierge'],
        romanticScore: 6.0,
        familyScore: 5.0,
        adventureScore: 4.0
    },
    {
        title: 'Secluded Treehouse',
        location: 'Bali, Indonesia',
        price: 120,
        rating: 4.95,
        type: 'Tropical',
        lat: -8.4095,
        lng: 115.1889,
        images: [
            'https://images.unsplash.com/photo-1488415032361-b7e238421f1b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
        ],
        amenities: ['Nature', 'WiFi', 'Breakfast', 'Hammock'],
        tags: ['tropical', 'treehouse', 'bali', 'indonesia', 'nature', 'adventure', 'romantic'],
        description: 'Experience nature like never before in this secluded treehouse. Surrounded by lush greenery and wildlife.',
        wifiStrength: 6.5,
        noiseLevel: 1.5,
        workspaceRating: 7.0,
        petAllowed: false,
        petSize: null,
        petAmenities: [],
        nearbyParks: false,
        spaceSize: 600,
        luxuryAmenities: ['Outdoor Shower'],
        romanticScore: 9.0,
        familyScore: 4.0,
        adventureScore: 9.8
    },
    {
        title: 'Beachfront Bungalow',
        location: 'Maui, Hawaii',
        price: 450,
        rating: 4.85,
        type: 'Amazing pools',
        lat: 20.7984,
        lng: -156.3319,
        images: [
            'https://images.unsplash.com/photo-1437719417032-8595fd9e9dc6?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1540541338287-41700207dee6?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
        ],
        amenities: ['Beach Access', 'Pool', 'WiFi', 'Kitchen', 'Kayaks'],
        tags: ['beach', 'ocean', 'hawaii', 'usa', 'tropical', 'family', 'adventure'],
        description: 'Wake up to the sound of waves in this beachfront bungalow. Direct access to the beach and stunning sunsets.',
        wifiStrength: 8.0,
        noiseLevel: 3.0,
        workspaceRating: 5.0,
        petAllowed: true,
        petSize: 'medium',
        petAmenities: ['Beach towel for dogs'],
        nearbyParks: true,
        spaceSize: 1500,
        luxuryAmenities: ['Private Beach', 'Jacuzzi'],
        romanticScore: 8.5,
        familyScore: 9.0,
        adventureScore: 9.0
    },
    {
        title: 'Historic Castle Stay',
        location: 'Edinburgh, Scotland',
        price: 600,
        rating: 5.0,
        type: 'Castles',
        lat: 55.9533,
        lng: -3.1883,
        images: [
            'https://images.unsplash.com/photo-1533154683836-84ea7a0bc310?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1585543805890-6051f7829f98?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
        ],
        amenities: ['History', 'Garden', 'WiFi', 'Library', 'Grand Hall'],
        tags: ['castle', 'historic', 'scotland', 'uk', 'luxury', 'romantic'],
        description: 'Live like royalty in this historic castle. Explore the grounds and enjoy the rich history of the area.',
        wifiStrength: 7.5,
        noiseLevel: 2.0,
        workspaceRating: 6.0,
        petAllowed: true,
        petSize: 'any',
        petAmenities: ['Large grounds'],
        nearbyParks: true,
        spaceSize: 8000,
        luxuryAmenities: ['Butler Service', 'Antique Furniture'],
        romanticScore: 9.2,
        familyScore: 8.0,
        adventureScore: 7.0
    },
    {
        title: 'Residency Hotel',
        location: 'Mumbai, India',
        price: 150,
        rating: 4.6,
        type: 'Iconic cities',
        lat: 19.0760,
        lng: 72.8777,
        images: [
            'https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
        ],
        amenities: ['City View', 'WiFi', 'Restaurant', 'Gym', 'Conference Room'],
        tags: ['city', 'urban', 'mumbai', 'india', 'business', 'hotel'],
        description: 'Enjoy a luxurious stay at the Residency Hotel in the heart of Mumbai. Close to business districts and tourist attractions.',
        wifiStrength: 9.0,
        noiseLevel: 6.0,
        workspaceRating: 9.0,
        petAllowed: false,
        petSize: null,
        petAmenities: [],
        nearbyParks: false,
        spaceSize: 400,
        luxuryAmenities: ['Room Service', 'Spa'],
        romanticScore: 5.0,
        familyScore: 6.0,
        adventureScore: 3.0
    },
    // New Targeted Listings for Advanced Filters
    {
        title: 'Digital Nomad Haven',
        location: 'Austin, Texas',
        price: 120,
        rating: 4.95,
        type: 'Tiny homes',
        lat: 30.2672,
        lng: -97.7431,
        images: [
            'https://images.unsplash.com/photo-1497366216548-37526070297c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1497215728101-856f4ea42174?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
        ],
        amenities: ['High-Speed WiFi', 'Ergonomic Chair', 'Monitor', 'Coffee Maker', 'Quiet'],
        tags: ['city', 'urban', 'texas', 'usa', 'business', 'modern', 'work'],
        description: 'The ultimate workspace for remote workers. Blazing fast fiber internet, soundproof walls, and a professional ergonomic setup.',
        wifiStrength: 10.0,
        noiseLevel: 1.0,
        workspaceRating: 10.0,
        petAllowed: false,
        petSize: null,
        petAmenities: [],
        nearbyParks: false,
        spaceSize: 400,
        luxuryAmenities: ['Espresso Machine', 'Standing Desk'],
        romanticScore: 3.0,
        familyScore: 2.0,
        adventureScore: 4.0
    },
    {
        title: 'Pet Paradise Ranch',
        location: 'Portland, Oregon',
        price: 180,
        rating: 4.8,
        type: 'Farms',
        lat: 45.5152,
        lng: -122.6784,
        images: [
            'https://images.unsplash.com/photo-1587595431973-160d0d94add1?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1516455590571-18256e5bb9ff?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
        ],
        amenities: ['Fenced Yard', 'Dog Run', 'Pet Spa', 'WiFi'],
        tags: ['farm', 'rural', 'oregon', 'usa', 'pet-friendly', 'nature', 'family'],
        description: 'A dream vacation for your furry friends. Acres of fenced land, agility course, and luxury pet beds provided.',
        wifiStrength: 7.0,
        noiseLevel: 4.0,
        workspaceRating: 5.0,
        petAllowed: true,
        petSize: 'any',
        petAmenities: ['Dog bed', 'Bowls', 'Toys', 'Agility Course', 'Pet Spa'],
        nearbyParks: true,
        spaceSize: 2500,
        luxuryAmenities: ['Pet Spa'],
        romanticScore: 5.0,
        familyScore: 9.0,
        adventureScore: 8.0
    },
    {
        title: 'Budget Backpacker Hostel',
        location: 'Bangkok, Thailand',
        price: 25,
        rating: 4.2,
        type: 'Shared homes',
        lat: 13.7563,
        lng: 100.5018,
        images: [
            'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
        ],
        amenities: ['WiFi', 'Shared Kitchen', 'Lockers'],
        tags: ['city', 'urban', 'bangkok', 'thailand', 'asia', 'budget', 'hostel'],
        description: 'Affordable stay in the heart of the city. Meet travelers from around the world.',
        wifiStrength: 8.0,
        noiseLevel: 8.0,
        workspaceRating: 4.0,
        petAllowed: false,
        petSize: null,
        petAmenities: [],
        nearbyParks: false,
        spaceSize: 200,
        luxuryAmenities: [],
        romanticScore: 2.0,
        familyScore: 3.0,
        adventureScore: 7.0
    },
    {
        title: 'Ultimate Luxury Penthouse',
        location: 'Dubai, UAE',
        price: 2500,
        rating: 5.0,
        type: 'Iconic cities',
        lat: 25.2048,
        lng: 55.2708,
        images: [
            'https://images.unsplash.com/photo-1512918760513-95f1929c3d09?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1600607686527-6fb886090705?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
        ],
        amenities: ['Infinity Pool', 'Helipad', 'Butler', 'Spa', 'Cinema'],
        tags: ['city', 'urban', 'dubai', 'uae', 'middle-east', 'luxury', 'penthouse'],
        description: 'Unmatched luxury in the sky. Private elevator, personal chef, and panoramic views of the skyline.',
        wifiStrength: 10.0,
        noiseLevel: 1.0,
        workspaceRating: 9.0,
        petAllowed: true,
        petSize: 'small',
        petAmenities: ['Gourmet Pet Food'],
        nearbyParks: true,
        spaceSize: 5000,
        luxuryAmenities: ['Helipad', 'Private Cinema', 'Butler Service', 'Sauna', 'Jacuzzi'],
        romanticScore: 9.5,
        familyScore: 6.0,
        adventureScore: 2.0
    },
    {
        title: 'Honeymoon Overwater Villa',
        location: 'Bora Bora, French Polynesia',
        price: 1200,
        rating: 5.0,
        type: 'Tropical',
        lat: -16.5004,
        lng: -151.7415,
        images: [
            'https://images.unsplash.com/photo-1439066615861-d1fb8bc3a78a?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1540541338287-41700207dee6?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
        ],
        amenities: ['Private Pool', 'Ocean Access', 'Room Service', 'Massage'],
        tags: ['tropical', 'ocean', 'island', 'french-polynesia', 'luxury', 'romantic', 'honeymoon'],
        description: 'The most romantic getaway on earth. Glass floors, sunset views, and complete privacy.',
        wifiStrength: 8.0,
        noiseLevel: 1.0,
        workspaceRating: 4.0,
        petAllowed: false,
        petSize: null,
        petAmenities: [],
        nearbyParks: false,
        spaceSize: 1000,
        luxuryAmenities: ['Private Pool', 'Jacuzzi', 'Champagne Service'],
        romanticScore: 10.0,
        familyScore: 4.0,
        adventureScore: 7.0
    },
    {
        title: 'Family Fun Resort Villa',
        location: 'Orlando, Florida',
        price: 400,
        rating: 4.7,
        type: 'Amazing pools',
        lat: 28.5383,
        lng: -81.3792,
        images: [
            'https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1584132967334-10e028bd69f7?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
        ],
        amenities: ['Themed Rooms', 'Game Room', 'Pool with Slide', 'Crib', 'High Chair'],
        tags: ['city', 'florida', 'usa', 'family', 'theme-park', 'resort'],
        description: 'Perfect for large families. Disney themed rooms, huge game room, and a pool with a water slide.',
        wifiStrength: 9.0,
        noiseLevel: 6.0,
        workspaceRating: 5.0,
        petAllowed: true,
        petSize: 'any',
        petAmenities: [],
        nearbyParks: true,
        spaceSize: 4000,
        luxuryAmenities: ['Game Room', 'Home Theater'],
        romanticScore: 3.0,
        familyScore: 10.0,
        adventureScore: 5.0
    },
    {
        title: 'Basecamp Adventure Lodge',
        location: 'Queenstown, New Zealand',
        price: 300,
        rating: 4.9,
        type: 'Cabins',
        lat: -45.0312,
        lng: 168.6626,
        images: [
            'https://images.unsplash.com/photo-1449156493391-d2cfa28e468b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1518623001395-1252423c0d0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
        ],
        amenities: ['Gear Storage', 'Boot Dryers', 'Hot Tub', 'Map Room'],
        tags: ['mountain', 'newzealand', 'adventure', 'ski', 'nature', 'outdoor'],
        description: 'Your gateway to adrenaline. Ski-in/ski-out, bike storage, and expert local guides available.',
        wifiStrength: 8.5,
        noiseLevel: 3.0,
        workspaceRating: 6.0,
        petAllowed: true,
        petSize: 'medium',
        petAmenities: ['Dog wash station'],
        nearbyParks: true,
        spaceSize: 2000,
        luxuryAmenities: ['Hot Tub', 'Sauna'],
        romanticScore: 6.0,
        familyScore: 7.0,
        adventureScore: 10.0
    },
];

const prisma = new PrismaClient();

console.log('Prisma keys:', Object.keys(prisma));

async function main() {
    console.log('Start seeding ...');

    // Create a default host user
    const host = await prisma.user.upsert({
        where: { email: 'host@example.com' },
        update: {},
        create: {
            email: 'host@example.com',
            name: 'Host User',
            password: 'password', // In a real app, hash this!
            image: 'https://i.pravatar.cc/150?u=host',
        },
    });

    console.log(`Created user with id: ${host.id}`);

    // Clear existing data
    console.log('Clearing existing data...');
    await prisma.reservation.deleteMany({});
    await prisma.favorite.deleteMany({});
    await prisma.listing.deleteMany({});
    console.log('Cleared existing listings and related data');

    for (const listing of mockListings) {
        const createdListing = await prisma.listing.create({
            data: {
                title: listing.title,
                description: listing.description,
                price: listing.price,
                location: listing.location,
                rating: listing.rating,
                type: listing.type || 'Entire home', // Default if missing
                lat: listing.lat,
                lng: listing.lng,
                images: listing.images,
                amenities: listing.amenities,
                tags: listing.tags || [],
                hostId: host.id,
                // New Advanced Filter Fields
                wifiStrength: listing.wifiStrength,
                noiseLevel: listing.noiseLevel,
                workspaceRating: listing.workspaceRating,
                petAllowed: listing.petAllowed,
                petSize: listing.petSize,
                petAmenities: listing.petAmenities,
                nearbyParks: listing.nearbyParks,
                spaceSize: listing.spaceSize,
                luxuryAmenities: listing.luxuryAmenities,
                romanticScore: listing.romanticScore,
                familyScore: listing.familyScore,
                adventureScore: listing.adventureScore,
            },
        });
        console.log(`Created listing with id: ${createdListing.id}`);
    }

    console.log('Seeding finished.');
}

main()
    .then(async () => {
        await prisma.$disconnect();
    })
    .catch(async (e) => {
        console.error(e);
        await prisma.$disconnect();
        process.exit(1);
    });
